version: '3'
services:

  cybernews-php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: digitalocean.com/php
    container_name: cybernews-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ".:/var/www"
      - "./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini"
    networks:
      - cybernews-network

  nginx:
    image: nginx:alpine
    container_name: cybernews-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ".:/var/www"
      - "./docker/nginx/conf.d:/etc/nginx/conf.d"
    networks:
      - cybernews-network

  mysql:
    image: mysql:latest
    container_name: cybernews-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_HOST=127.0.0.1
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
      - SERVICE_NAME=MYSQL
#    volumes:
#      - "./docker/mysql/dbdata:/var/lib/mysql"
#      - "./docker/mysql/my.cnf:/etc/mysql/my.cnf"
    networks:
      - cybernews-network


networks:
  cybernews-network:
    driver: bridge